#pragma once
#include "GameInstance.h"

namespace Client
{
	enum LEVEL { LEVEL_STATIC, LEVEL_LOADING, 
                 LEVEL_LOGO = 2, 
                 LEVEL_GAMEPLAY, 

                //============= TOOL
                 LEVEL_TOOL_FX,
                 LEVEL_TOOL_UI,
                 LEVEL_TOOL_ANIM = 6, // ANIM툴은 6으로 고정 ! 부탁드립니댜
                 LEVEL_TOOL_MAP,

                 LEVEL_PARTTIME,
                //============ GAME
                 LEVEL_INTRO,
                 LEVEL_RACING,
                 LEVEL_DEEDEEDEE,

                 LEVEL_TOWN,
                 LEVEL_PARK,

                 LEVEL_SIMBA,
                 LEVEL_FINALBOSS, // 리소스명 LAB_DISCOVERA
                 LEVEL_FINALE,

                 LEVEL_END };

    enum TRIGGER_TYPE { TRIGGER_CAMERA, TRIGGER_SHADER, TRIGGER_STAR, TRIGGER_LEVELCHANGER, TRIGGER_MONSTER, TRIGGER_SIMBA_ATTACK, TRIGGER_EVENT, TRIGGER_END };
    enum CAMERA_TYPE  { CAM_FRONT, CAM_REAR, CAM_END };

    enum KIRBY_EVENT
    {
        KEVENT_DDD_BATTLESTART,
        KEVENT_DDD_DEAD,

        KEVENT_BREAK_CARSHOP,
        KEVENT_BREAK_RACINGMAP,

        KEVENT_SIMBA_APPEAR_START,
        KEVENT_SIMBA_NEXT_DIALOG1,
        KEVENT_SIMBA_NEXT_DIALOG2,
        KEVENT_SIMBA_LAST_DIALOG,
        KEVENT_SIMBA_APPEAR_END,
        KEVENT_SIMBA_WAVE1DEAD,
        KEVENT_SIMBA_WAVE2DEAD,
        KEVENT_SIMBA_THRONEBREAK,
        KEVENT_SIMBA_GLASSBREAK,
        KEVENT_SIMBA_BOSSORIGIN,
        KEVENT_SIMBA_CAGEBREAK,

        KEVENT_FINALBOSS_APPEAR,
        KEVENT_FINALBOSS_BATTLESTART,

        KEVENT_END
    };
    
    const unsigned int	g_iWinSizeX = 1600; //1280;
    const unsigned int	g_iWinSizeY = 900;  //720;

    const float g_fCamFar = 20000.f;

    const wstring g_strLayerMonster = TEXT("Layer_Monster");
    const wstring g_strLayerItem = TEXT("Layer_Item");
    const wstring g_strLayerMapObject = TEXT("Layer_MapObject");
}

extern HWND g_hWnd;
extern HINSTANCE g_hInst;

using namespace std;
using namespace Client;

#define ADD_GAMEOBJECT_PROTOTYPE(tag, className) \
    do { \
        wstring wstrResult = L"Prototype_GameObject_" + wstring(tag); \
        if (FAILED(m_pGameInstance->Add_Prototype(wstring(wstrResult), className::Create(m_pDevice, m_pContext)))) \
            return E_FAIL; \
    } while (0)

#define AXIS_X 1.f, 0.f, 0.f, 0.f
#define AXIS_Y 0.f, 1.f, 0.f, 0.f
#define AXIS_Z 0.f, 0.f, 1.f, 0.f

// SOUND MACRO
#define VOLUME_BGM          0.5f
#define VOLUME_BGM_SUB      0.4f


enum PASS_POSTEX {
    POSTEX_DEFAULT, POSTEX_SOLIDBLEND, POSTEX_BLENDFX, POSTEX_BLOOM, POSTEX_DEFAULTFX, POSTEX_SOLIDBLEND_NOZTEST,
    POSTEX_WHITEFX, POSTEX_UI_MASK, POSTEX_UI_MASK2, POSTEX_SOFTFX, POSTEX_SOFTALPHAFX, POSTEX_UIWHITEALPHA, POSTEX_ALPHABLEND_NOTEST,
    POSTEX_ALPHATEST_COLOR, POSTEX_ALPHATEST_COLOR_HORIZONTALCUT, POSTEX_BOSS_BARPASS_DEFAULT, POSTEX_ALPHATEST_COLOR_VERTICALCUT,
    POSTEX_FOCUSINGPOSITION, POSTEX_FADEINOUT, POSTEX_UIMWBASE_CLAW, POSTEX_QTEBASE, POSTEX_QTEPLATE, POSTEX_QTEEFFECT,
    POSTEX_SPAWNEFFECT, POSTEX_BLENDFX_SOFTEFFECT_X,
    POSTEX_END
};

enum PASS_MODEL {
    MODEL_NORMAL_O, MODEL_NORMAL_X, MODEL_SHADOW, MODEL_SKY, MODEL_BLOOM, MODEL_NONBLUR, MODEL_TRIGGER = 6, 
    MODEL_ALPHABLEND, MODEL_DEFERREDINFO, MODEL_NEARCLIP, MODEL_KIRBYPART, MODEL_MONSTERPART,
    MODEL_DEFAULTFX = 12, MODEL_BLENDFX_LINEARDIFFUSE, MODEL_BLENDFX_CLAMPDIFFUSE, MODEL_WHITEFX_LINEARDIFFUSE, MODEL_WHITEFX_CLAMPDIFFUSE, MODEL_EMISSIVE_NORMAL_O, MODEL_EMISSIVE_NORMAL_X,
    MODEL_STAR, MODEL_COIN, MODEL_DISSOLVE, MODEL_WHITE_FX_LINEARDIFFUSE_LINEARMASK, MODEL_WHITE_FX_CLAMPDIFFUSE_LINEARMASK, MODEL_FOR_LASER, MODEL_PARKDECO_NONDISCARD,
    MODEL_END
};

enum PASS_MAP {
    MAP_NONBLEND_NORMAL_O, MAP_NONBLEND_NORMAL_X, MAP_LIGHTDEPTH, MAP_ALPHABLEND, MAP_NONBLEND_NONDISCARD, MAP_MASKED_NORMAL_O,
    MAP_EMISSIVE_NORMAL_O, MAP_EMISSIVE_NORMAL_X, MAP_SIMBA_ROCK,
    MAP_END
};

enum PASS_ANIMMODEL {
    ANIMMODEL_NORMAL_O, ANIMMODEL_NORMAL_X, ANIMMODEL_SHADOW, ANIMMODEL_MOUTH, ANIMMODEL_EYE, ANIMMODEL_BLOOM, ANIMMODEL_BLEND, ANIMMODEL_DEFERREDINFO,
    ANIMMODEL_KIRBY, ANIMMODEL_KIRBYMOUTH, ANIMMODEL_KIRBYEYE, ANIMMODEL_NEARCLIP, ANIMMODEL_LINEAR_NORMAL_O, ANIMMODEL_KIRBY_WEAPONS, ANIMMODEL_FINALEKIRBY_WEAPONS
    , ANIMMODEL_ALPHABLEND, ANIMMODEL_LINEAR_NORMAL_O_NONDISCARD, ANIMMODEL_SIMBAEYE, ANIMMODEL_BULBLIGHT, ANIMMODEL_POPSTAR, ANIMMODEL_EMISSIVE,
    ANIMMODEL_DEFORMRIM, ANIMMODEL_GLASSCRACK, ANIMMODEL_DIMENSIONGATE, ANIMMODEL_SIMBAEYE_DEFAULT, ANIMMODEL_ANTENNA,
    ANIMMODEL_END
};

enum PASS_INSTANCEPOINT {
    INSTANCEPOINT_DEFAULT, INSTANCEPOINT_DEFAULTFX, INSTANCEPOINT_WHITEFX, INSTANCEPOINT_BLENDFX, 
    INSTANCEPOINT_FOG,
    INSTANCEPOINT_END
};

enum ABILITYTYPE {
    ABILITY_DEFAULT, ABILITY_SWORD, ABILITY_HAMMER, ABILITY_BOMB, ABILITY_CRASH, ABILITY_END
};

enum VACUUMSIZE {
    SIZE_SMALL, SIZE_BIG, SIZE_END
};

enum PHYXOBJECT_CURSTATE {
    PO_NORMAL, PO_VACUUMING, PO_KIRBYMOUTH, PO_FLYAWAY, PO_FLYDEADAWAY, PO_PRESSED, PO_END
};

enum COLLISION_TYPE
{
    PLAYER, 
    PLAYERBULLET,
    MONSTER,
    MONSTERBULLET,
    BOSS_DEEDEEDEE,
    BOSS_FINALBOSS,
    BOSS_SIMBA,
    OBJECT, // 돌멩이 등 사물이다.
    BOXOBJECT, // 상자따위의 부숴지는 물체이다. (몬스터를 날리면 부딫히는애들)
    ITEM, // 일반 먹는 아이템이다.
    ABILITYITEM, // 흡수해야 먹을 수 있는 능력 아이템이다.
    DEFORMOBJECT, // 머금기 오브젝트들
    FINALGM,
    NPC, // 마을에 있는 NPC
    DEE, // 마을에 있는 일반 디
    BATTLEDEE, //디디디랑싸우는디
    HITBOX_PLYAER,
    HITBOX_MONSTER,
    HITBOX_DEEDEEDEE,
    HITBOX_SIMBA,
    LASER_SIMBA,
    ANIMDECO, // 애니메이션 있는 풀, 상자 등등
    TRIGGER_FOR_NOT_PHYSX,

    FINALE_PLAYER,
    FINALE_BAUM,
    FINALE_BREAKABLEBLOCK,
    FINALE_BIGBAUM,

    COLLISION_END
};
