#pragma once

#include "Client_Defines.h"
#include "Monster.h"

BEGIN(Engine)
class CModel;
class CShader;
class CPartObject;
END

BEGIN(Client)

class CFinalBoss final : public CMonster
{
public:
	enum FINALBOSS_ANIM {
		FINALBOSS_APPEAR,					FINALBOSS_AWAYFAST,						FINALBOSS_AWAYFASTEND,			FINALBOSS_AWAYFASTENDAIR,	
		FINALBOSS_AWAYFASTREADY,			FINALBOSS_AWAYFASTSTART,				FINALBOSS_BALLWAIT,				FINALBOSS_BIGAPPEAR,				FINALBOSS_BIGCHAINLR, 
		FINALBOSS_BIGCHAINRL,				FINALBOSS_BIGROAR,						FINALBOSS_BIGSWINGFINISHLEFT,	FINALBOSS_BIGSWINGFINISHLEFTEND,
		FINALBOSS_BIGSWINGLEFT,				FINALBOSS_BIGSWINGLEFTEND,				FINALBOSS_BIGSWINGLEFTSTART,	FINALBOSS_BIGSWINGRIGHT,			FINALBOSS_BIGSWINGRIGHTEND, 
		FINALBOSS_BIGSWINGRIGHTSTART,		FINALBOSS_BIGWAITAIR,					FINALBOSS_CHAINLR,				FINALBOSS_CHAINRL,					FINALBOSS_DAMAGE, DAMAGEAIR, 
		FINALBOSS_DAMAGEFACESUB,			FINALBOSS_DEMOAPPEARCUT1,				FINALBOSS_DEMOAPPEARCUT2,		FINALBOSS_DEMOAPPEARCUT3,			FINALBOSS_DEMOAPPEARCUT4,
		FINALBOSS_DEMOAPPEARCUT5,			FINALBOSS_DEMOAPPEARSOULCUT2,			FINALBOSS_DEMOAPPEARSOULCUT3,	FINALBOSS_DEMODISAPPEARCUT2,		FINALBOSS_DEMODISAPPEARCUT3,
		FINALBOSS_DEMODISAPPEARCUT8,		FINALBOSS_DEMODISAPPEARCUT8WAIT,		FINALBOSS_DEMODISAPPEARCUT9,	FINALBOSS_DEMODISAPPEARCUT9WAIT,	FINALBOSS_DEMODISAPPEARSOULCUT1,
		FINALBOSS_DIMENSIONLASER,			FINALBOSS_DIMENSIONLASERCHARGE,			FINALBOSS_DIMENSIONLASEREND,	FINALBOSS_DIMENSIONLASEREADY,		FINALBOSS_DIMENSIONLASERSTART,
		FINALBOSS_DIMENSIONSPIKE,			FINALBOSS_DIMENSIONSPIKEEND,			FINALBOSS_DIMENSIONSPIKEREADY,	FINALBOSS_DIMENSIONSPIKEREADYWAIT,	FINALBOSS_DIMENSIONSPIKESTART,
		FINALBOSS_DIMENSIONSPIKEWAIT,		FINALBOSS_FALL,							FINALBOSS_FLASHTHRUST,			FINALBOSS_FLASHTHRUSTEND,			FINALBOSS_FLASHTHRUSTREADY,
		FINALBOSS_FLASHTHRUSTSTART,			FINALBOSS_FLASHTHRUSTSWINGFINISHLEFT,	FINALBOSS_JUMPEND,				FINALBOSS_JUMPREADY,				FINALBOSS_JUMPSTART,
		FINALBOSS_LASTDAMAGEAIRFALL,		FINALBOSS_LASTDAMAGEAIRSTART,			FINALBOSS_LASTDAMAGESTART,		FINALBOSS_LASTDAMAGEWAIT,			FINALBOSS_MOVEFAST,
		FINALBOSS_MOVEFASTEND,				FINALBOSS_MOVEFASTREADY,				FINALBOSS_MOVEFASTSTART,		FINALBOSS_MOVESLOW,					FINALBOSS_RAYARROWEND,
		FINALBOSS_RAYARROWENDAIR,			FINALBOSS_RAYARROWREADY,				FINALBOSS_RAYARROWREADYAIR,		FINALBOSS_RAYARROWSTART,			FINALBOSS_RAYARROWSTARTAIR,
		FINALBOSS_RAYARROWWAIT,				FINALBOSS_RAYARROWWAITAIR,				FINALBOSS_RECOVERYEND,			FINALBOSS_RECOVERYSTART,			FINALBOSS_RECOVERYWAIT,
		FINALBOSS_RESIST,					FINALBOSS_RESISTFALL,					FINALBOSS_RESISTLOOP,			FINALBOSS_RESISTSTART,				FINALBOSS_RESISTSUCCESS,
		FINALBOSS_ROAR,						FINALBOSS_SLASH,						FINALBOSS_SLASHCHAINREADY,		FINALBOSS_SLASHCHAINSTABREADY,		FINALBOSS_SLASHEND, 
		FINALBOSS_SLASHREADY,				FINALBOSS_SLASHSTART,					FINALBOSS_STAB,					FINALBOSS_STABEND,					FINALBOSS_STABREADY,
		FINALBOSS_STABSTART,				FINALBOSS_STABWAIT,						FINALBOSS_SUMMON,				FINALBOSS_SUMMONEND,				FINALBOSS_SUMMONSTART,
		FINALBOSS_SUMMONWAIT,				FINALBOSS_SWINGFINISHLEFT,				FINALBOSS_SWINGFINISHLEFTEND,	FINALBOSS_SWINGLEFT,				FINALBOSS_SWINGLEFTEND, 
		FINALBOSS_SWINGLEFTSTART,			FINALBOSS_SWINGRIGHT,					FINALBOSS_SWINGRIGHTEND,		FINALBOSS_SWINGRIGHTSTART,			FINALBOSS_TESTANIM01,
		FINALBOSS_TURNLEFTAIR,				FINALBOSS_TURNLEFTAIREND,				FINALBOSS_TURNLEFTAIRSTART,		FINALBOSS_TURNRIGHTAIR,				FINALBOSS_TURNRIGHTAIREND,
		FINALBOSS_TURNRIGHTAIRSTART,		FINALBOSS_WAIT,							FINALBOSS_WAITAIR,
		FINALBOSS_END
	};

	enum FINALBOSS_STATE { STATE_FLYING, STATE_GROUND, STATE_2PAZE, STATE_END };

	struct FINALBOSS_DESC : public CMonster::MONSTER_DESC {
		vector<_float4> vecRallyPoints;
	};

private:
	CFinalBoss(ID3D11Device* pDevice, ID3D11DeviceContext* pContext);
	CFinalBoss(const CFinalBoss& rhs);
	virtual ~CFinalBoss() = default;

public:
	void Set_Direction(_vector vDir) { m_vDir = vDir; }
	void Set_BossState(FINALBOSS_STATE eBossState) { m_eBossState = eBossState; }
	void Set_Glide(_bool bGlide) { m_bGlide = bGlide; }
	void Set_Chain(_bool bChain) { m_bChain = bChain; }
	void Set_TickPerSecond(_float TickPerSecond) { m_pModelCom->Set_TickPerSecond(TickPerSecond); }
	void Set_Position(_vector vPosition) { m_vPosition = vPosition; }

	_vector Get_Direction() { return m_vDir; }
	_vector Get_Position() { return m_vPosition; }
	vector<_float4> Get_RallyPoint() { return m_vecRallyPoint; }
	FINALBOSS_STATE Get_BossState() { return m_eBossState; }
	_bool Get_Chain() { return m_bChain; }

public:
	virtual HRESULT Initialize_Prototype() override;
	virtual HRESULT Initialize(void* pArg) override;
	virtual _int	Tick(_float fTimeDelta) override;
	virtual void	Late_Tick(_float fTimeDelta) override;
	virtual HRESULT Render() override;
	virtual HRESULT Render_LightDepth() override;
#ifdef _DEBUG
	virtual void	Render_IMGUI() override;
#endif
	virtual void	Collision(CCollisionCenter::CONTENT_TYPE eContent, CPhysXObject* pObject) override;

public:
	void Change_State(FINALBOSS_ANIM eState, _float _fAnimSpeed, _bool _bLoop, _bool _bInterpolation);
	_bool IsAnimFinished();

private:
	map<const wstring, CPartObject*>	m_PartObjects;

	FINALBOSS_ANIM		m_eCurrentState = { FINALBOSS_END };
	FINALBOSS_STATE		m_eBossState = { STATE_END };

	vector<_float4>		m_vecRallyPoint;

	_vector				m_vDir = {};
	_vector				m_vPosition = {};

	_bool				m_bGlide = { false };
	_bool				m_bChain = { false };

	_float				m_fGlideTime = { 0.f };

private:
	HRESULT	Make_TargetToCams();

	HRESULT Add_Components();
	HRESULT Add_PartObjects();
	HRESULT Bind_ShaderResources();

	// FSM
	void SetUp_FSM();

public:
	static CFinalBoss* Create(ID3D11Device* pDevice, ID3D11DeviceContext* pContext);
	virtual CGameObject* Clone(void* pArg) override;
	virtual void Free() override;
};

END