#pragma once

enum DIR { DIR_LEFT, DIR_RIGHT, DIR_FRONT, DIR_BACK, DIR_LF, DIR_RF, DIR_LB, DIR_RB, DIR_END };

enum STATE {
	// 죽음과 직결되는 애니메이션
	STATE_DAMAGE = 7, //(원래 32인데...)
	STATE_DEATH = 33,
	STATE_DEATHWAIT = 35,
	STATE_DYINGWAIT = 51,
	STATE_EATDAMAGE = 53,
	STATE_FILGHTDAMAGE = 83,

	// 닷지 (회피) 관련 애니메이션 36 ~ 48
	STATE_DODGEBACK = 36, STATE_DODGEBACK1, STATE_DODGEBACK2,
	STATE_DODGEFRONT, STATE_DODGEFRONT1, STATE_DODGEFRONT2,
	STATE_DODGELEFT, STATE_DODGELEFT1, STATE_DODGELEFT2,
	STATE_DODGERIGHT, STATE_DODGERIGHT1, STATE_DODGERIGHT2,
	STATE_DODGESTART = 48,

	// 먹은 상태의 애니메이션 (BALLOON)
	STATE_EAT = 52, STATE_EATFALL = 56, STATE_EATJUMP, STATE_EATLANDING, STATE_EATRUN,
	STATE_EATWAIT = 65,
	STATE_FLIGHTSTART = 90,
	STATE_FLIGHT = 82, STATE_FLIGHTFALL = 84,
	STATE_FLIGHTLANDING = 86,
	STATE_FLIGHTLIMIT = 87, STATE_FLIGHTLIMITFALL = 88,

	// 흡수 상태의 애니메이션 (VACUUM)
	STATE_INHALE = 117, STATE_INHALEEND, STATE_INHALEFALL, STATE_INHALELV2, STATE_INHALELANDING,
	STATE_INHALESTART = 123, STATE_INHALEWALK = 124,
	STATE_SPIT = 189, STATE_SPITAIR = 190,
	STATE_SUPERINHALE = 222, STATE_SUPERINHALELANDING = 224, STATE_SUPERINHALESTART = 225, STATE_SUPERINHALEWALK = 226,

	// 획득 관련 애니메이션
	STATE_GETABILITY = 107, STATE_ITEMGET = 126, STATE_ITENGETWAIT = 127,

	// 기본 Default 기본 애니메이션
	STATE_JUMP = 130, STATE_JUMPEND = 131, STATE_JUMPFALL = 134, STATE_JUMPL, STATE_JUMPR,
	STATE_LADDERDOWN = 138, STATE_LADDERUP = 141, STATE_LADDERWAIT = 142, STATE_LADDERWAITSTATR = 143,
	STATE_LANDINGEND = 145, STATE_LANDINGSMALL = 146,
	STATE_FALL = 76,
	STATE_IDLE = 256, STATE_RUN = 172, STATE_RUNSTART = 173,
	STATE_IDLESTREACH = 259, STATE_IDLELOOKAROUND = 260,

	// 기본 액션 공격
	STATE_GUARD = 109, STATE_SLIDE = 179, STATE_SLIDEEND, STATE_SLIDESTART,

	// 감정표현
	STATE_WAITYAY = 264, STATE_WAITSIT = 257, STATE_EMOTEWAVEHAND = 70,

	STATE_END = 291
};

enum EYESTATE { EYE_IDLE, EYE_ANGER, EYE_CLOSE, EYE_SADNESS, EYE_PUPIL, EYE_BLINK, EYE_END };
enum MOUTHSTATE { MOUTH_IDLE, MOUTH_ANGER, MOUTH_HAPPY, MOUTH_SMILE, MOUTH_SURPRISE, MOUTH_END };
enum BODYSTATE { BODY_DEFAULT, BODY_BALLOON, BODY_VACUUM, BODY_END };

