#pragma once

enum DIR { DIR_LEFT, DIR_RIGHT, DIR_FRONT, DIR_BACK, DIR_LF, DIR_RF, DIR_LB, DIR_RB, DIR_END };

enum STATE {
	// 죽음과 직결되는 애니메이션
	STATE_DAMAGE = 7, //(원래 32인데...)
	STATE_DEATH = 33,
	STATE_DEATHWAIT = 35,
	STATE_DYINGWAIT = 51,
	STATE_EATDAMAGE = 53,
	STATE_FILGHTDAMAGE = 83,

	// 닷지 (회피) 관련 애니메이션 36 ~ 48
	STATE_DODGEBACK = 36, STATE_DODGEBACK1, STATE_DODGEBACK2,
	STATE_DODGEFRONT, STATE_DODGEFRONT1, STATE_DODGEFRONT2,
	STATE_DODGELEFT, STATE_DODGELEFT1, STATE_DODGELEFT2,
	STATE_DODGERIGHT, STATE_DODGERIGHT1, STATE_DODGERIGHT2,
	STATE_DODGESTART = 48,

	// 먹은 상태의 애니메이션 (BALLOON)
	STATE_EAT = 52, STATE_EATFALL = 56, STATE_EATJUMP, STATE_EATLANDING, STATE_EATRUN,
	STATE_EATWAIT = 65,
	STATE_FLIGHTSTART = 90,
	STATE_FLIGHT = 82, STATE_FLIGHTFALL = 84,
	STATE_FLIGHTLANDING = 86,
	STATE_FLIGHTLIMIT = 87, STATE_FLIGHTLIMITFALL = 88,
	STATE_SWALLOWSTART = 236, STATE_SWALLOWEND = 235,

	// 흡수 상태의 애니메이션 (VACUUM)
	STATE_INHALE = 117, STATE_INHALEEND, STATE_INHALEFALL, STATE_INHALELV2, STATE_INHALELANDING,
	STATE_INHALESTART = 123, STATE_INHALEWALK = 124,
	STATE_SPIT = 189, STATE_SPITAIR = 190,
	STATE_SUPERINHALE = 222, STATE_SUPERINHALELANDING = 224, STATE_SUPERINHALESTART = 225, STATE_SUPERINHALEWALK = 226,
	// 몬스터와 상호작용하는 특수 애니메이션 (VACUUMING)
	STATE_VACUUM = 250, STATE_VACUUMHUSTLELV2 = 252,

	// 획득 관련 애니메이션
	STATE_GETABILITY = 107, STATE_ITEMGET = 126, STATE_ITENGETWAIT = 127,
	STATE_ABILITYDUMP = 0,

	// 기본 Default 기본 애니메이션
	STATE_JUMP = 130, STATE_JUMPEND = 131, STATE_JUMPFALL = 134, STATE_JUMPL, STATE_JUMPR,
	STATE_LADDERDOWN = 138, STATE_LADDERUP = 141, STATE_LADDERWAIT = 142, STATE_LADDERWAITSTART = 143,
	STATE_LANDINGEND = 145, STATE_LANDINGSMALL = 146,
	STATE_FALL = 76,
	STATE_IDLE = 256, STATE_RUN = 172, STATE_RUNSTART = 173,
	STATE_IDLESTREACH = 259, STATE_IDLELOOKAROUND = 260,

	// 기본 액션 공격
	STATE_GUARD = 109, STATE_SLIDE = 179, STATE_SLIDEEND, STATE_SLIDESTART,

	// 감정표현
	STATE_WAITYAY = 264, STATE_WAITSIT = 257, STATE_EMOTEWAVEHAND = 70,


	// 칼 모션.
	SWORDSTATE_DECISIVESLASH = 300, SWORDSTATE_GIGANTSPINSLASH,
	SWORDSTATE_GUARD,
	SWORDSTATE_HAVESWORDWAITFLIGHT = 304,

	SWORDSTATE_MULITSWORDATTACK = 306, SWORDSTATE_RUN,
	SWORDSTATE_SHUFFIEFRONT = 309, SWORDSTATE_SHUFFIERIGHT, SWORDSTATE_SIDESLASH, SWORDSTATE_SIDESLASHEND,
	SWORDSTATE_SPINSLASH, SWORDSTATE_SPINSLASHCHARGE, SWORDSTATE_SPINSLASHEND, SWORDSTATE_SUPERSPINSLASHCHARGE,
	SWORDSTATE_SUPERSPINSLASHCHARGESTART, SWORDSTATE_SUPERSPINSLASHEND, SWORDSTATE_SUPERSPINSLASHLOOP, SWORDSTATE_SUPERSPINSLASHSTART,

	SWORDSTATE_SWORDDIVE = 322, 
	SWORDSTATE_SWORDSLIDE, SWORDSTATE_SWORDSLIDEEND, SWORDSTATE_SWORDSLIDESTART, 
	SWORDSTATE_SWORDSPIN,SWORDSTATE_SWORDSPINSTART, 
	SWORDSTATE_UPWARDSLASH, SWORDSTATE_WAIT,
	SWORDSTATE_SPINAFTER = 305,

	// 폭탄 모션
	BOOMSTATE_BOOMFALL = 352, BOOMSTATE_BOOMSHOOT = 360, BOOMSTATE_THROW = 362,
	BOOMSTATE_THROWAIR = 363, BOOMSTATE_THROWCHARGE = 364, BOOMSTATE_THROWROTATE = 367,

	// Deform 을 뱉는 모션
	STATE_SPITDEFORM = 191,
	// 자동차 모션
	CARSTATE_BOOST = 400, CARSTATE_BOOSTEND = 401, CARSTATE_CRASH = 403,
	CARSTATE_DAMAGE = 405,
	CARSTATE_DEMOEND = 410,
	CARSTATE_FALL = 412, CARSTATE_JUMPSTART = 416, CARSTATE_JUMP = 415, CARSTATE_IDLING = 414,
	CARSTATE_LANDING = 417, CARSTATE_MOVING = 419, CARSTATE_CUT2 = 423, CARSTATE_CUT1 = 424,

	// 자동차 흡수 모션
	CARVACUUMSTATE_DEFORM = 450, CARVACUUMSTATE_DEFORMFIRST = 451,

	// 해머폼
	HAMMERSTATE_HAMMERATTACKFINALTOY = 505, HAMMERSTATE_HAMMERATTACKHITTOY = 507, 
	HAMMERSTATE_HAMMERATTACKSTARTTOY = 512, HAMMERSTATE_HAMMERATTACKTOY = 513,
	HAMMERSTATE_ONIGOROSIHAMMERCHARGE = 516, HAMMERSTATE_ONIGOROSIHAMMEREND = 517, HAMMERSTATE_ONIGOROSIHAMMERFIRST = 518, 
	HAMMERSTATE_ONIGOROSIHAMMERMOVE = 522, HAMMERSTATE_ONIGOROSIHAMMERSTART = 526, 
	HAMMERSTATE_WHEELHAMMER = 531, HAMMERSTATE_WHEELHAMMEREND = 532,

	HAMMERSTATE_JUMPEND = 535, HAMMERSTATE_JUMPL = 537, HAMMERSTATE_JUMPR, HAMMERSTATE_LANDINGEND, HAMMERSTATE_LANDINGSMALL,
	HAMMERSTATE_RUN , HAMMERSTATE_IDLE,

	// 전구폼
	BULBSTATE_DAMAGE = 550, BULBSTATE_DEATH, BULBSTATE_DEATHWAIT, BULBSTATE_DEMOENDFIRST = 554, BULBSTATE_FALL = 556,
	BULBSTATE_HIGHTOUCH, BULBSTATE_JUMP, BULBSTATE_LANDING, BULBSTATE_LANDINGBRIGHT, BULBSTATE_LANDINGEND, BULBSTATE_LANDINGENDBRIGHT,
	BULBSTATE_LIGHTOFF, BULBSTATE_LIGHTON, BULBSTATE_LIGHTONAIR, BULBSTATE_MOVE, BULBSTATE_MOVEBRIGHT, BULBSTATE_STOP, BULBSTATE_STOPBRIGHT,
	BULBSTATE_WAIT, BULBSTATE_WAITBRIGHT,

	// 전구 흡수 폼
	BULBVACUUMSTATE_DEFORM = 600,

	STATE_END = 5000
};

enum EYESTATE { EYE_IDLE, EYE_ANGER, EYE_CLOSE, EYE_SADNESS, EYE_PUPIL, EYE_BLINK, EYE_DOUBT, EYE_END };
enum MOUTHSTATE { MOUTH_IDLE, MOUTH_ANGER, MOUTH_HAPPY, MOUTH_SMILE, MOUTH_SURPRISE, MOUTH_END };

enum BODYSTATE { BODY_DEFAULT, BODY_BALLOON, BODY_VACUUM, 
				BODY_SWORDDEFAULT, BODY_SWORDBALLOON, BODY_BOOMDEFAULT, 
				BODY_CARDEFAULT, BODY_CARVACUUM, BODY_HAMMER, BODY_BULBDEFAULT, BODY_BULBVACUUM,
				BODY_END };

enum KIRBYOFFSET { 
	OFFSET_SWORD = 300, OFFSET_BOOM = 350, OFFSET_CAR = 400, OFFSET_CARVACUUM = 450, OFFSET_HAMMER = 500,
	OFFSET_BULB = 550, OFFSET_BULBVACUUM = 600,
	OFFSET_END
};


