#pragma once
#include "Client_Defines.h"
#include "Monster.h"

BEGIN(Engine)
class CModel;
class CShader;
class CTexture;
END

BEGIN(Client)

class CSimba final : public CMonster
{
public:
	enum SIMBA_ANIM {
		SIMBA_ATTACKJUMP, SIMBA_ATTACKJUMPEND, SIMBA_ATTACKJUMPHIT, SIMBA_ATTACKJUMPPRE, SIMBA_ATTACKJUMPSTART, SIMBA_ATTACKJUMPWAIT,
		SIMBA_BACKSTEP, SIMBA_BACKSTEPEND, SIMBA_BACKSTEPLANDING, SIMBA_BACKSTEPSTART,
		SIMBA_BITERUSH, SIMBA_BITERUSHEND, SIMBA_BITEFALLL, SIMBA_BITEFALLR,
		SIMBA_BITERUSHJUMPL, SIMBA_BITERUSHJUMPR, SIMBA_BITERUSHJUMPSTARTL, SIMBA_BITERUSHJUMPSTARTR,
		SIMBA_BITERUSHLANDINGL, SIMBA_BITERUSHLANDINGR, SIMBA_BITERUSHSTART, SIMBA_BITERUSHSTARTSTRAIGHT,
		SIMBA_BITERUSHTIREDATTACKSTART, SIMBA_BITERUSHTIREDATTACKSTARTSTRAIGHT, 
		SIMBA_BITERUSHTIREDEND, SIMBA_BITERUSHTIREDSTART, SIMBA_BITERUSHTIREDWAIT,
		SIMBA_COMMAND, 
		SIMBA_DAMAGE, SIMBA_DAMAGEFACESUB,
		SIMBA_DEATH,
		SIMBA_DEMOAPPEAR1CUT10, SIMBA_DEMOAPPEAR1CUT10WAIT, 
		SIMBA_DEMOAPPEAR1CUT2, SIMBA_DEMOAPPEAR1CUT2WAIT,
		SIMBA_DEMOAPPEAR1CUT3, SIMBA_DEMOAPPEAR1CUT3WAIT, 
		SIMBA_DEMOAPPEAR1CUT4, SIMBA_DEMOAPPEAR1CUT4WAIT,
		SIMBA_DEMOAPPEAR1CUT6, SIMBA_DEMOAPPEAR1CUT6WAIT, 
		SIMBA_DEMOAPPEAR1CUT9, SIMBA_DEMOAPPEAR1CUT9WAIT,
		SIMBA_DEMOAPPEAR2CUT1, SIMBA_DEMOAPPEAR2CUT2,
		SIMBA_DEMODEADCUT1, SIMBA_DEMODEADCUT2,
		SIMBA_DEMOEXAPPEARCUT1, SIMBA_DEMOEXAPPEARCUT2, SIMBA_DEMOEXAPPEARCUT3, SIMBA_DEMOEXAPPEARCUT4, SIMBA_DEMOEXAPPEARCUT5, 
		SIMBA_DEMOEXAPPEARCUT6, SIMBA_DEMOEXAPPEARCUT6MULTI, SIMBA_DEMOEXAPPEARCUT7, SIMBA_DEMOEXAPPEARCUTPREWAIT,
		SIMBA_DEMOMORPHOKNIGHTAPPPEARCUT1, SIMBA_DEMOMORPHOKNIGHTAPPPEARCUT2, SIMBA_DEMOMORPHOKNIGHTAPPPEARCUT3, SIMBA_DEMOMORPHOKNIGHTAPPPEARCUT4, SIMBA_DEMOMORPHOKNIGHTAPPPEARCUT5,
		SIMBA_DEMOSOULAPPEARCUT1, SIMBA_DIMENSIONCLAW, SIMBA_DIMENSIONCLAWCONTINUE, SIMBA_DIMENSIONCLAWEND, SIMBA_DIMENSIONCLAWSTART, SIMBA_DIMENSIONCLAWSTARTCONTINUE, SIMBA_DIMENSIONCLAWWAIT,
		SIMBA_DIMENSIONLASER, SIMBA_DIMENSIONLASEREND, SIMBA_DIMENSIONLASERSTART, SIMBA_DIMENSIONLASERWAIT,
		SIMBA_DOUBLECLAW, SIMBA_DOUBLECLAWCHARGESTART, SIMBA_DOUBLECLAWCHARGEWAIT, SIMBA_DOUBLECLAWDASH, SIMBA_DOUBLECLAWDASHSTART, SIMBA_DOUBLECLAWEND,
		SIMBA_FALL, 
		SIMBA_FINALCRUSHER, SIMBA_FINALCRUSHEREND, SIMBA_FINALCRUSHERREPEAT, 
		SIMBA_FINALCRUSHERSTART, SIMBA_FINALCRUSHERSTARTCONTINUE, SIMBA_FINALCRUSHERSTARTREPEAT, SIMBA_FINALCRUSHERSTARTREPEATEND,
		SIMBA_JUMP, SIMBA_JUMPSTART,
		SIMBA_KNEEL, SIMBA_KNEELEND, SIMBA_KNEELSTART,
		SIMBA_LANDING,
		SIMBA_LIPSYNCSUB, SIMBA_LIPSYNCSUBA,
		SIMBA_MOUTHSUB,
		SIMBA_QUICKCLAW2L, SIMBA_QUICKCLAW2R, SIMBA_QUICKCLAWAGAINL, SIMBA_QUICKCLAWAGAINR, SIMBA_QUICKCLAWCHARGEL, SIMBA_QUICKCLAWCHARGER,	
		SIMBA_QUICKCLAWENDL, SIMBA_QUICKCLAWENDR, SIMBA_QUICKCLAWL, SIMBA_QUICKCLAWFROMSTART, SIMBA_QUICKCLAWR, 
		SIMBA_QUICKCLAWREPEATL, SIMBA_QUICKCLAWREPEATR,	SIMBA_QUICKCLAWRFROMSTART, SIMBA_QUICKCLAWSTARTL, SIMBA_QUICKCLAWSTARTR,
		SIMBA_ROAR, SIMBA_ROAR2, SIMBA_ROAR2LONG, SIMBA_ROAR2SOUL,
		SIMBA_SIT,
		SIMBA_WAIT1, SIMBA_WAIT2,
		SIMBA_WALK,
		SIMBA_END
	};

	enum SIMBA_EYETEX { EYETEX_DIFFUSE, EYETEX_NORMAL, EYETEX_MRA, EYETEX_END };
	enum SIMBA_EYESTATE { SIMBAEYE_LONG, SIMBAEYE_SMALL, SIMBAEYE_BIG, SIMBAEYE_END };

private:
	CSimba(ID3D11Device* pDevice, ID3D11DeviceContext* pContext);
	CSimba(const CSimba& rhs);
	virtual ~CSimba() = default;

public:
	void Set_SimbaEye(SIMBA_EYESTATE eEyeState) { m_eEyeState = eEyeState; }

	_float4 Get_Pos() { return m_vPos; }

public:
	virtual HRESULT Initialize_Prototype()			override;
	virtual HRESULT Initialize(void* pArg)			override;
	virtual _int	Tick(_float fTimeDelta)			override;
	virtual void	Late_Tick(_float fTimeDelta)	override;
	virtual HRESULT Render()						override;
	virtual HRESULT Render_LightDepth()				override;
#ifdef _DEBUG
	virtual void	Render_IMGUI()					override;
#endif
	virtual void	Add_AnimEvent()					override;
	virtual void	Collision(CCollisionCenter::CONTENT_TYPE eContent, CPhysXObject* pObject) override;

public:
	void			Change_State(SIMBA_ANIM eState, _float _fAnimSpeed, _bool _bLoop, _bool _bInterpolation);
	_bool			IsAnimFinished() { return m_pModelCom->IsFinished(); }
	_bool			IsAnimFinished(_uint iCurrentAnimIndex) { return m_pModelCom->IsFinished(iCurrentAnimIndex); }

private:
	CTexture*		m_pEyeTextureCom[EYETEX_END] = { nullptr, nullptr, nullptr };
	CModel*			m_pFaceModelCom = { nullptr };

	SIMBA_ANIM		m_eCurrentState = { SIMBA_END };
	SIMBA_EYESTATE	m_eEyeState = { SIMBAEYE_END };

	vector<_uint>	m_vecMeshes;
	_uint			m_iEyeMesh = {};
	_uint			m_iEyeLidMesh = {};

	_bool			m_bPlayFaceAnim = { false };

	_float			m_fAngle = { 0.f };
	_float4			m_vPos = {};

	vector<_uint>	m_vecValidBoneIndices;

private:
	HRESULT			Add_Components();
	HRESULT			Bind_ShaderResources();

	// FSM
	void			SetUp_FSM();

public:
	static CSimba* Create(ID3D11Device* pDevice, ID3D11DeviceContext* pContext);
	virtual CGameObject* Clone(void* pArg) override;
	virtual void Free() override;
};

END
